name: "build"
on:
  release:
    types: [published]
  push:
  pull_request:
permissions:
  contents: read
jobs:
  build-macos:
    name: Build for MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          ENV: CI
        run: |
          mkdir -p dist/
          make -j 4 dist/package.zip
          make test
      - name: Upload dist as artifact
        uses: actions/upload-artifact@v2
        with:
          name: lines0-darwin-amd64
          path: dist
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          ENV: CI
        run: |
          mkdir -p dist/
          make -j 4 dist/package.zip
          make test
      - name: Upload dist as artifact
        uses: actions/upload-artifact@v2
        with:
          name: lines0-linux-amd64
          path: dist
  build-sqljs:
    name: Build for SQL.JS/WASM
    steps:
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 1.38.40
          actions-cache-folder: "emsdk-cache"
      - uses: actions/checkout@v2
      - run: |
          mkdir -p dist/
          make -j 4 wasm
      - uses: actions/upload-artifact@v2
        with:
          name: lines0-sqljs.js
          path: dist/sqljs.js
      - uses: actions/upload-artifact@v2
        with:
          name: lines0-sqljs.wasm
          path: dist/sqljs.wasm
  release:
    name: "releases"
    if: ${{ github.event_name == 'release' }}
    needs: [build-macos, build-linux, build-sqljs]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download workflow artifacts
        uses: actions/download-artifact@v2
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./release.js')
            await script({github, context})
