on: [push]
name: "build"
jobs:
  build-macos:
    name: Build for MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          ENV: CI
        run: |
          mkdir -p dist/
          make dist/package.zip
          make test
      - name: Upload dist as artifact
        uses: actions/upload-artifact@v2
        with:
          name: lines0-darwin-amd64
          path: dist
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          ENV: CI
        run: |
          mkdir -p dist/
          make dist/package.zip
          make test
      - name: Upload dist as artifact
        uses: actions/upload-artifact@v2
        with:
          name: lines0-linux-amd64
          path: dist
  release:
    name: "releases"
    if: ${{ github.event_name == 'release' }}
    needs: [build-macos, build-linux]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download workflow artifacts
        uses: actions/download-artifact@v2
      - name: Upload release artifacts
      - uses: actions/checkout@v2
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./release.js')
            await script({github, context})
