on: [push]
name: "build"
jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          #- os: ubuntu-latest
          #  asset: sqlite-html0-linux-amd64
          # 2022 uses python 3.9, which we need to have json funcs in sqlite for test.py.
          #- os: windows-2022
          #  asset: sqlite-html0-windows
          - os: macos-latest
            asset: sqlite-lines

    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          ENV: CI
        run: |
          wget -q https://www.sqlite.org/2022/sqlite-amalgamation-3380500.zip
          unzip sqlite-amalgamation-3380500.zip
          mv sqlite-amalgamation-3380500 sqlite
          rm sqlite-amalgamation-3380500.zip
          mkdir -p dist/
          make dist/package.zip
          make test
      - name: distribution
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.asset}}
          path: dist
