on: [push]
name: "build"
jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset: linux-sqlite-lines0
          - os: macos-latest
            asset: macos-sqlite-lines0

    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          ENV: CI
        run: |
          mkdir -p dist/
          make dist/package.zip
          make test
      - name: distribution
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.asset}}
          path: dist
